### ISSUE TITLE
At ByteBufferUtils.deserialize, NumberFormatException occurred

### ISSUE THREAD

**Issue by z3guru** [z3guru/temple.toolkit#3]
java.lang.NumberFormatException: For input string: "1 "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at guru.z3.temple.toolkit.nio.ByteBufferUtils.deserialize(ByteBufferUtils.java:36)

**Comment by z3guru** [comment]
fix bug, deploy as soon as possible
